jack_stat_daily_iv_index:
    pattern: /daily/iv/index
    defaults: { _controller: JackStatisticBundle:DailyIV:index }

jack_stat_daily_iv_display:
    pattern: /daily/iv/display/{action}/{symbol}
    defaults: { _controller: JackStatisticBundle:DailyIV:display }

jack_stat_hv_index:
    pattern: /hv/generate/index
    defaults: { _controller: JackStatisticBundle:HV:index }

jack_stat_hv_result:
    pattern: /hv/generate/{action}/{sample}/{symbol}
    defaults: { _controller: JackStatisticBundle:HV:result }

jack_stat_pcratio_index:
    pattern: /pcratio/generate/index
    defaults: { _controller: JackStatisticBundle:pcRatio:index }

jack_stat_pcratio_result:
    pattern: /pcratio/generate/result/{symbol}
    defaults: { _controller: JackStatisticBundle:pcRatio:result }
