jack_earning:
    resource: "@JackEarningBundle/Resources/config/routing.yml"
    prefix:   /earning

jack_default:
    resource: "@JackDefaultBundle/Resources/config/routing.yml"
    prefix:   /default

jack_find:
    resource: "@JackFindBundle/Resources/config/routing.yml"
    prefix:   /find

jack_statistic:
    resource: "@JackStatisticBundle/Resources/config/routing.yml"
    prefix:   /stat

jack_import:
    resource: "@JackImportBundle/Resources/config/routing.yml"
    prefix:   /import

jack_system:
    resource: "@JackSystemBundle/Resources/config/routing.yml"
    prefix:   /system

jack_service:
    resource: "@JackServiceBundle/Resources/config/routing.yml"
    prefix:   /service
