jack_default:
    resource: "@JackDefaultBundle/Resources/config/routing.yml"
    prefix:   /jack/default

jack_find:
    resource: "@JackFindBundle/Resources/config/routing.yml"
    prefix:   /jack/find

jack_statistic:
    resource: "@JackStatisticBundle/Resources/config/routing.yml"
    prefix:   /jack/stat

jack_import:
    resource: "@JackImportBundle/Resources/config/routing.yml"
    prefix:   /jack/import

jack_system:
    resource: "@JackSystemBundle/Resources/config/routing.yml"
    prefix:   /jack/system

jack_service:
    resource: "@JackServiceBundle/Resources/config/routing.yml"
    prefix:   /jack/service
