jack_import:
    resource: "@JackImportBundle/Resources/config/routing.yml"
    prefix:   /jack/import

jack_system:
    resource: "@JackSystemBundle/Resources/config/routing.yml"
    prefix:   /jack/system

jack_service:
    resource: "@JackServiceBundle/Resources/config/routing.yml"
    prefix:   /jack/service
