jack_find_underlying_index:
    pattern:  /underlying
    defaults: { _controller: JackFindBundle:Underlying:index }

jack_find_underlying_result_findbyall:
    pattern:  /underlying/result/findbyall/{symbol}
    defaults: { _controller: JackFindBundle:Underlying:result, action: findbyall }

jack_find_underlying_result_findbyday:
    pattern:  /underlying/result/findbyday/{day}/{symbol}
    defaults: { _controller: JackFindBundle:Underlying:result, action: findbyday }

jack_find_underlying_result_findbymonth:
    pattern:  /underlying/result/findbymonth/{month}/{symbol}
    defaults: { _controller: JackFindBundle:Underlying:result, action: findbymonth }

jack_find_underlying_result_findbyyear:
    pattern:  /underlying/result/findbyyear/{year}/{symbol}
    defaults: { _controller: JackFindBundle:Underlying:result, action: findbyyear }

jack_find_underlying_result_findbyweekday:
    pattern:  /underlying/result/findbyweekday/{weekday}/{symbol}
    defaults: { _controller: JackFindBundle:Underlying:result, action: findbyweekday }

jack_find_underlying_result_findbyweek:
    pattern:  /underlying/result/findbyweek/{week}/{symbol}
    defaults: { _controller: JackFindBundle:Underlying:result, action: findbyweek }

jack_find_underlying_result_findbycalendar:
    pattern:  /underlying/result/findbycalendar/{year}/{month}/{day}/{weekday}/{week}/{symbol}
    defaults: { _controller: JackFindBundle:Underlying:result, action: findbycalendar }

jack_find_underlying_result_findbydaterange:
    pattern:  /underlying/result/findbydaterange/{firstDate}/{lastDate}/{symbol}
    defaults: { _controller: JackFindBundle:Underlying:result, action: findbydaterange }

jack_find_underlying_result_daterange_redirect:
    pattern:  /underlying/result/findbydaterange/redirect/{symbol}
    defaults: { _controller: JackFindBundle:Underlying:dateRangeRedirect, action: findbydaterange }





index:
    pattern: /index
    defaults: { _controller: JackFindBundle:Cycle:index }

result:
    pattern: /result
    defaults: { _controller: JackFindBundle:Cycle:result }
