parameters:
#    jack_find.example.class: Jack\FindBundle\Example

services:
#    jack_find.example:
#        class: %jack_find.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
