jack_earning_default_index:
    pattern:  /default/index
    defaults: { _controller: JackEarningBundle:Default:index }

jack_earning_default_result:
    pattern:  /default/result/{symbol}
    defaults: { _controller: JackEarningBundle:Default:result }

jack_earning_estimate_price_result:
    pattern: /estimate/price/report/{from}/{to}/{backward}/{forward}/{format}/{symbol}
    defaults: { _controller: JackEarningBundle:Estimate:priceResult, from: 'last', to: 'last', forward: 0, backward: 0, format: 'medium' }

jack_earning_estimate_price_redirect:
    pattern: /estimate/price/report/redirect
    defaults: { _controller: JackEarningBundle:Estimate:resultRedirect }

jack_earning_sweetspot_result:
    pattern: /sweetspot/result/index/{type}/{strategy}/{enter}/{exit}/{backward}/{forward}/{format}/{symbol}
    defaults: { _controller: JackEarningBundle:SweetSpot:sweetSpotResult, type: 'edge', strategy: 'bullish', enter: 'last', exit: 'last', forward: 0, backward: 0, format: 'medium' }

jack_earning_sweetspot_redirect:
    pattern: /sweetspot/result/redirect
    defaults: { _controller: JackEarningBundle:SweetSpot:redirect }
