jack_import_default:
    pattern:  /default
    defaults: { _controller: JackImportBundle:Default:index }

jack_import_check_form:
    pattern: /check/form
    defaults: { _controller: JackImportBundle:Check:form }

jack_import_check_report:
    pattern: /check/report/{name}
    defaults: { _controller: JackImportBundle:Check:report }

jack_import_event_symbol:
    pattern: /event/select/symbol
    defaults: { _controller: JackImportBundle:Event:selectSymbol }


jack_import_event_add:
    pattern: /event/add/{symbol}
    defaults: { _controller: JackImportBundle:Event:addEvent }

jack_import_event_add_earning:
    pattern: /event/add/earning/{symbol}
    defaults: { _controller: JackImportBundle:Event:addEarning }

jack_import_event_add_analyst:
    pattern: /event/add/analyst/{symbol}
    defaults: { _controller: JackImportBundle:Event:addAnalyst }


jack_import_event_manage:
    pattern: /event/manage/{symbol}
    defaults: { _controller: JackImportBundle:Event:manageEvent }

jack_import_event_remove:
    pattern: /event/remove/{symbol}/{id}/{redirect}
    defaults: { _controller: JackImportBundle:Event:removeEvent }
